### ISSUE TITLE
Makes a non-interactive box instead of an overlay.

### ISSUE THREAD

**Issue by hailwood** [Rickgbw/hyperterm-overlay#13]
The screenshot explains it - that box is meant to be the overlay but instead I just get that and as you can see the main window still hangs around.
![overlay-bug](https://cloud.githubusercontent.com/assets/709773/17660446/7c7c8590-632d-11e6-8974-a746f332eda5.png)

Ubuntu 16.04 running Unity.
I get this on both my home and work computers.

**Comment by rickgbw** [comment]
@hailwood, could you check if latest version (0.4.0) fix this?

**Comment by zfwf** [comment]
OS: Ubuntu 16.04
hyperterm-overlay: 0.4.0
hyperterm: 1.4.2

@hailwood Unable to repeat with the above setup. Can you please update `hyper` and `hyperterm-overlay` (in `hyper` use the `Ctrl+Shift+U` to force plugin update) and try again?

**Comment by hailwood** [comment]
Sorry folks,

I don't use hyper anymore. Given that no one else has reported this issue I'd say we're safe to close it as something specific to my setup.

--
Matt
