### ISSUE TITLE
Blank terminal window

### ISSUE THREAD

**Issue by jcoetzee** [Rickgbw/hyperterm-overlay#16]
I get a blank terminal window when I activate this plugin. Not sure if I'm doing something wrong. Hyper 0.8.1 on OS X 10.11. I use fish shell if that makes any difference.

![screen shot 2016-10-07 at 11 41 05 am](https://cloud.githubusercontent.com/assets/1784961/19186055/a9f790ac-8c84-11e6-9486-ceca085438f6.png)

```
overlay: {
  unique: true,
  animate: false,
  // hideDock: true,
  startAlone: true,
  startup: true
},
```

`plugins: ['hyperterm-overlay'],`

**Comment by jcoetzee** [comment]
It works if I open a new tab. Seems it isn't opening an initial tab on startup.

**Comment by reneruiz** [comment]
I think development on this plugin is dead.

**Comment by jcoetzee** [comment]
Yeah, unfortunate cuz I really like the plugin in general, can't live without visor terminal.

**Comment by rickgbw** [comment]
I will try to check this issue soon. 
I also accept PRs if someone already fix...
