### ISSUE TITLE
Unexpected Identifier?

### ISSUE THREAD

**Issue by dieggsy** [Rickgbw/hyperterm-overlay#18]
I get the messsage "An error occured in your configuration: Unexpected Identifier" when I copy the config from the ReadMe. Unsure what's going on.

**Comment by jdinhify** [comment]
@therockmandolinist one possibility is that there's a comma missing just before the overlay config you paste in

**Comment by dieggsy** [comment]
You know, I'm pretty sure that _was_ it. I feel silly now. Thanks!
