### ISSUE TITLE
Gnome supports

### ISSUE THREAD

**Issue by baptistedonaux** [Rickgbw/hyperterm-overlay#27]
Reading the documentation, I thought that this plugin supports only mac OS but I see also this issue #23  and I don't know anymore…

Do you support Gnome environment ?

**Comment by rickgbw** [comment]
This plugin is not well tested on other OS, but this not mean we cannot work this support (PRs, issues, helps...)

**Comment by baptistedonaux** [comment]
Alright ! I'll try to help this project for Debian support.
