### ISSUE TITLE
Return focus to previous window on hide

### ISSUE THREAD

**Issue by mattapperson** [Rickgbw/hyperterm-overlay#3]
Comments on how to do this can be found here https://github.com/zeit/hyperterm/issues/398

**Comment by albinekb** [comment]
try doing this:

```
const { Menu } = require('electron')
Menu.sendActionToFirstResponder('hide:')
```

Or from the render process:

```
const { Menu } = require('electron').remote
Menu.sendActionToFirstResponder('hide:')
```

**Comment by rickgbw** [comment]
Done. Seems to work as expected, thanks for this suggestion

**Comment by rickgbw** [comment]
I put a little check to detect if should focus on internal hyperterm window or an external one.(32ff15862d1e5947925aa2d138268dcc7f89bb22)

**Comment by Angush** [comment]
Is there any way this can be done on Windows? I haven't found any, myself, but I may just be a terrible Googler.
