### ISSUE TITLE
More control over size and position

### ISSUE THREAD

**Issue by gattazr** [Rickgbw/hyperterm-overlay#33]
Currently, there are 4 possible positions (`top`, `right`, `bottom`, `left`) and 1 parameter (`size`) to control the size of the window.

`size` is used to control either the width of the window or its height depending on where it's positioned. If the position is top or bottom, it controls the height. If it's left or right, it controls the width. This is done in the function [`_endBounds `](https://github.com/rickgbw/hyperterm-overlay/blob/master/overlay.js#L226)

<br>

It would be awesome to introduce the positions `topLeft`, `topRight`, `bottomLeft` and `bottomRight` and the parameters `width` and `height` to give much more control over the window's size and position.

Here a few bullet points to explain a bit what I have in mind : 
- With the hyper window is configured to be in one of those new position, the values of `width` and `height will simply control the width and height of the window. They will both be used.

- When the hyper windows is configured to be in one of the currently existing positions, either `width` or `height` will be ignored depending on which position it is. As an example, when the position top is used, the width configuration value is ignored and the window's width will be set to the maximum.

- Keeping a retro-compatibility with `size` can be done. It is just a matter of loading `size` into either `width` or `height` depending on the position and if the value doesn't already exist. Still, with a change like this, `size` should become deprecated and eventually be deleted.

These few points can be summarized like this :-) 

| Position         | `height` | `width` | `size`                 |
|--------------|----------|---------|-----------------|
| top                 | ✅            | 🔴          | `height = size`  |
| topRight        | ✅            | ✅          | 🔴                        |
| right              | 🔴            | ✅          | `width = size`    |
| bottomRight | ✅            | ✅          | 🔴                        |
| bottom          | ✅            | 🔴          | `height = size` |
| bottomLeft   | ✅            | ✅          | 🔴                         |
| left                | 🔴            | ✅          | `width = size`    |
| topLeft         | ✅            | ✅          | 🔴                         |

A possible evolution would be to enable both `width` and `height` for the 4 existing position and consider that the window should be centered with 2 margins. I wouldn't be a big step from what I've just described but I think that it's going a bit too far and it would be possible to add that later.

<br>

With this idea, the default configuration would then go from this :
```js
overlay: {
  position: 'top',
  size: 0.4,
},
```

To either on of the following 3 since they are equivalent :
```js
overlay: {
  position: 'top',
  height: 0.4,
},
```
```js
overlay: {
  position: 'topLeft',
  height: 0.4,
  width: 1.0,
},
```
```js
overlay: {
  position: 'topRight',
  height: 0.4,
  width: 1.0,
},
```

**Comment by favna** [comment]
Project is probably dead considering the commits and issues but this is fixed in #45.

I have also published my fork to the NPM registry as [hyper-overlay](https://www.npmjs.com/package/hyper-overlay) so you can also add that instead to have these options. I'm not sure if I'll make time to check out some of the other issues, but it does seem like a nice idea for this awesome plugin.
