### ISSUE TITLE
Fix left width

### ISSUE THREAD

**Issue by michaelstephens** [Rickgbw/hyperterm-overlay#37]
Hey! I love this plugin! Amazing work!

I noticed that at the very left side, there is just a few pixels of empty space:

<img width="175" alt="screen shot 2017-08-19 at 6 17 36 pm" src="https://user-images.githubusercontent.com/1581475/29491268-d232ca8a-850a-11e7-9247-b1d46814c0c3.png">

Is this something that's fixable? I noticed a few other "visor" plugins have this issue as well. 

Thanks!

**Comment by peterdanis** [comment]
Hi,
you can adjust it by yourself: search for "padding" setting in Hyperterm config file (.hyper.js). I think the default is 6px. 

![image](https://user-images.githubusercontent.com/26599181/30609826-b09c9984-9d7c-11e7-8df5-fcb9a2b63422.png)

**Comment by simonhaenisch** [comment]
I don't have that issue.

**Comment by michaelstephens** [comment]
I have discovered that it’s because of the dock. When the doc is hidden by default on the left side on the same screen as hyper, the os defaults to give a bit of space. It’s possible to override since iterm does it, but it’s pretty nit picky. Closing for now.
