### ISSUE TITLE
Window doesn't stay on top

### ISSUE THREAD

**Issue by RedBeardCory** [Rickgbw/hyperterm-overlay#41]
Even with alwaysOnTop set to true in the config, clicking on other windows will bring them to the front and hyper will be covered instead of staying on top as expected. 

This is on Ubuntu (17.04 64 bit) with the Gnome X11 desktop environment. 

Here is an example of what happens below:
![screenshot from 2017-10-26 11-47-00](https://user-images.githubusercontent.com/22898984/32030160-e550b0a4-ba44-11e7-92c3-ae97fd9a489f.png)

**Comment by favna** [comment]
Your config is wrong. Validate your JS before making issues (Atom is showing you the red squiggles for a reason!). You need to move the options to right under this comment but above the closing brace

![](https://favna.s-ul.eu/a6CK30MB.png)

**Comment by RedBeardCory** [comment]
Thanks for your help @Favna .
The JSON structure has nothing wrong with it syntactically, the red squiggles are purely bracket matchers in the theme I'm using.
The overlay config did however have to be put in the config object. I did not realise that the "plugins", "localPlugins" and "keymaps" objects were outside of this main config object.
