### ISSUE TITLE
IMPORTANT TO OTHER ISSUE READERS

### ISSUE THREAD

**Issue by favna** [Rickgbw/hyperterm-overlay#46]
If it isn't obvious on your first sight into the issues and pull requests list as well as the time it has been since @rickgbw last committed any code to this project, this project has clearly been deserted. I have therefore taken it upon myself to try and fix various issues (so far I have addressed / fixed #7, #14, #32, #33, #38, #39, #41, #42, #43 and #45).

You can find my fork [here on npm](https://www.npmjs.com/package/hyper-overlay) or [here on github](https://github.com/favna/hyper-overlay)

**Comment by jcklpe** [comment]
@Favna How do we install it? I've only ever installed hyper plugins through the plugin array in the dotfile.

**Comment by jcklpe** [comment]
Oh I see, you changed the name from hyperterm-overlay, to hyper-overlay. Cool. Got it!

Annnnd, now Hyper won't load my config files at all and is starting up in powershell mode. Ugh.... Man.... I don't know if this is worth it. I think I'm going to drop Hyper, it's just so poorly maintained that any little update breaks half the plugins.
