### ISSUE TITLE
Terminal doesn't show on linux (Ubuntu 15.10)

### ISSUE THREAD

**Issue by BenoitAverty** [Rickgbw/hyperterm-overlay#5]
I installed this plugin on linux and it doesn't seem to work.
- When I press the sortcut, an Icon appears in the tray but the terminal itself doesn't appear.
- Pressing the shortcut again starts a second tray icon

Additionally, the tray icon isn't practical to use. Clicking it shows a menu with one item 'open hyperterm overlay', instead of directly showing the overlay like in your gif.

**Comment by rickgbw** [comment]
I confess that I didn't test on linux yet... only on macOS.
I will try to do this soon :)

**Comment by rickgbw** [comment]
I have made some tests on Ubuntu 16.04 LTS and I did some changes.
Now it has a better treatment on linux, but tray icons still replicates when hyperterm close and open again.
Talking about clicking on tray icon, it seems to be an electron limitation on linux (https://github.com/electron/electron/blob/master/docs/api/tray.md#tray).
One solution for now, is deactivate tray, setting on `overlay` config:

``` js
overlay: {
   tray: false
}
```

... but I still looking to make it perform even better on linux.

**Comment by BenoitAverty** [comment]
Awesome, I'll test this later and report. I'm perfectly fine with not using the tray, I don't have it with guake.

**Comment by BenoitAverty** [comment]
Ok at first I thought it didn't work, but then I realized the config object was not preperly placed in my .hyperterm.js ... I'm closing this issue as it is solved. The only remaining one is the tray icon duplicating and not responding to clicks (which is indeed an electron issue)

**Comment by rickgbw** [comment]
Thanks for your reply @BenoitAverty 
I will keep looking for a solution on linux tray bug.
