### ISSUE TITLE
Closing last window makes it impossible to open a new window

### ISSUE THREAD

**Issue by mAAdhaTTah** [Rickgbw/hyperterm-overlay#8]
These are my settings:

```
    overlay: {
      animate: true,
      alwaysOnTop: true,
      hasShadow: true,
      hideOnBlur: true,
      hideDock: true,
      hotkeys: ['Ctrl+`'],
      resizable: true,
      position: 'top',
      primaryDisplay: true,
      startup: true,
      size: 0.4,
      tray: true,
      unique: true
    }
```

If I ever accidentally close the last window, hitting the hotkey doesn't create a new hotkey window. Because I have `hideDock` to true, I can't even closer Hyperterm and reopen it to get it back. I need to force quit from the Activity Monitor.

**Comment by rickgbw** [comment]
Fixed :)
I moved the "creatingWindow" control to a better place.
With `unique` true, it was removing the own overlay window, when trying to re-create.

**Comment by mAAdhaTTah** [comment]
Great, thanks!
