### ISSUE TITLE
Start HyperTerm overlay only.

### ISSUE THREAD

**Issue by BenoitAverty** [Rickgbw/hyperterm-overlay#9]
It would be awesome to have an option to start Hyperterm Overlay only, without forcing the overlay to be the only window.

A possible way this would work : 
- Starting Hyperterm when there is no other window would start the overlay only
- Starting Hyperterm when the overlay is already running would start hyperterm the normal way.

This would only be if a particular option is set of course.

**Comment by ppot** [comment]
@Rickgbw  I created a local branch addressing the issue. However I can't add a branch to make a pull request.

**Comment by BenoitAverty** [comment]
@ppot You have to fork the repository and create your branch on your own version of the repo. Then you'll be able to push this branch and make a pull request.

**Comment by ppot** [comment]
First time doing a Fork. Add some issues with commit messages using Fix. Should be fine.

**Comment by ppot** [comment]
@BenoitAverty Should be up if you want to see.

**Comment by BenoitAverty** [comment]
I'll try to test this when I have a moment. I'm not familiar enough with hyperterm and hyperterm-overlay to tell you if it works by looking at the code only ^^

**Comment by mattapperson** [comment]
@ppot This looks good to me (not that I have any real say on a PR ;) ) but I would suggest another config prop name? Perhaps `onlyStartupWin`? onStartup is a little ambiguous IMHO

**Comment by ppot** [comment]
@mattapperson Ya I know, but he seem to be not responding!

**Comment by rickgbw** [comment]
Sorry for late response :)
I agree with @mattapperson, "onStartup" is a little strange...

**Comment by rickgbw** [comment]
@ppot, looking at PR, we already have a code to remove the startup windows [here](https://github.com/Rickgbw/hyperterm-overlay/blob/master/overlay.js#L126), but is used for "unique" option. Maybe we just need to consider a "startAlone" option on this same condition.

**Comment by rickgbw** [comment]
Fixed. Renamed the option to `startAlone`
